"""add local authentication

Revision ID: 618fe1fa310c
Revises: 0004_guest_sessions
Create Date: 2026-09-09 09:19:57.729802
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '618fe1fa310c'
down_revision: Union[str, Sequence[str], None] = '0004_guest_sessions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_auth0_sub', sa.String(length=255), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('last_used_at', sa.Float(), nullable=True),
    sa.Column('revoked_at', sa.Float(), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_auth0_sub'], ['users.auth0_sub'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index('ix_auth_sessions_expires_at', 'auth_sessions', ['expires_at'], unique=False)
    op.create_index('ix_auth_sessions_user', 'auth_sessions', ['user_auth0_sub'], unique=False)
    op.add_column('users', sa.Column('password_hash', sa.Text(), nullable=True))
    op.add_column('users',sa.Column('email_verified',sa.Boolean(),nullable=False,server_default=sa.false(),),)    # ### end Alembic commands ###
    op.alter_column('users','email_verified',server_default=None,)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'password_hash')
    op.drop_index('ix_auth_sessions_user', table_name='auth_sessions')
    op.drop_index('ix_auth_sessions_expires_at', table_name='auth_sessions')
    op.drop_table('auth_sessions')
    # ### end Alembic commands ###
